Repository devruso/bibliotech, pull requests merged in 2023-04, with the labels that each got.

#24 Modal dos livros
  package-lock.json
  package.json
  src/components/ModalLivro/ModalLivro.css
  src/components/ModalLivro/ModalLivro.jsx
  src/pages/Livros/Livros.jsx
Labels: documentation, enhancement

#25 Remoção do material ui
  package-lock.json
  package.json
Labels: enhancement

#26 quiz de literatura
  src/App.jsx
  src/assets/images/quiz.png
  src/components/Menu/Menu.jsx
  src/data/quiz.js
  src/pages/BemVindo/BemVindo.css
  src/pages/BemVindo/BemVindo.jsx
  src/pages/Quiz/Quiz.css
  src/pages/Quiz/Quiz.jsx
Labels: documentation, enhancement

#29 Correção do trocar do e-mail - task 13
  src/firebase/user.js
  src/pages/PerfilUsuario/PerfilUsuario.jsx
Labels: documentation

#30 login com o github
  package-lock.json
  src/assets/icons/github.svg
  src/firebase/auth.js
  src/pages/Login/Login.jsx
Labels: documentation, enhancement

#34 Task politica de privacidade
  package-lock.json
  src/App.jsx
  src/pages/Login/Login.jsx
  src/pages/PoliticaPrivacidade/PoliticaPrivacidade.css
  src/pages/PoliticaPrivacidade/PoliticaPrivacidade.jsx
Labels: documentation, enhancement

#36 Upload de foto de perfil
  src/firebase/user.js
  src/pages/PerfilUsuario/PerfilUsuario.css
  src/pages/PerfilUsuario/PerfilUsuario.jsx
  src/pages/UploadFoto/UploadFoto.css
  src/pages/UploadFoto/UploadFoto.jsx
Labels: documentation, enhancement

#37 Task help page
  src/App.jsx
  src/components/Footer/Footer.jsx
  src/pages/Ajuda/Ajuda.css
  src/pages/Ajuda/Ajuda.jsx
  src/pages/PoliticaPrivacidade/PoliticaPrivacidade.jsx
Labels: documentation, enhancement

#38 Chat
  package-lock.json
  package.json
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/components/PasswordField/PasswordField.jsx
  src/firebase/collections.js
  src/firebase/mensagens.js
  src/pages/Chat/Chat.css
  src/pages/Chat/Chat.jsx
Labels: documentation, enhancement

#40 Foto de perfil na navbar
  src/components/Menu/Menu.css
  src/components/Menu/Menu.jsx
Labels: documentation, enhancement

#46 verificacao de email, apos cadastro
  src/App.jsx
  src/components/Footer/Footer.css
  src/components/Loader/Loader.jsx
  src/firebase/firebaseError.js
  src/pages/Cadastro/Cadastro.jsx
  src/pages/EmailVerification/EmailVerification.jsx
  src/pages/Login/Login.jsx
  src/pages/NotFound/NotFound.css
  src/pages/Reportar/Reportar.css
  src/pages/Reportar/Reportar.jsx
Labels: documentation, enhancement

#47 recurso de recuperação de senha
  src/App.jsx
  src/components/Menu/Menu.css
  src/firebase/user.js
  src/pages/Login/Login.jsx
  src/pages/RecuperacaoSenha/RecuperacaoSenha.css
  src/pages/RecuperacaoSenha/RecuperacaoSenha.jsx
  src/pages/UploadFoto/UploadFoto.jsx
Labels: documentation, enhancement

#48 Implementar conteúdos da Home
  src/firebase/auth.js
  src/firebase/collections.js
  src/firebase/user.js
  src/pages/Home/Home.jsx
Labels: enhancement

#49 Componente de post e correcao de bugs
  src/components/Footer/Footer.jsx
  src/components/PasswordField/PasswordField.jsx
  src/components/Postagem/Postagem.css
  src/components/Postagem/Postagem.jsx
  src/firebase/blog.js
  src/firebase/collections.js
  src/pages/Chat/Chat.css
  src/pages/Chat/Chat.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.css
  src/pages/Login/Login.jsx
Labels: documentation, enhancement

#50 Paginação de empréstimos, correção do CSS da página livros
  src/components/ModalLivro/ModalLivro.css
  src/pages/Emprestimos/Emprestimos.jsx
Labels: documentation, enhancement

#51 alterações no quiz e no search
  src/data/quiz.js
  src/pages/BemVindo/BemVindo.jsx
  src/pages/Livros/Livros.jsx
  src/pages/Quiz/Quiz.jsx
Labels: documentation, enhancement

#52 correcoes de mais alguns bugs
  src/components/Postagem/Postagem.css
  src/components/Postagem/Postagem.jsx
  src/index.css
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/RecuperacaoSenha/RecuperacaoSenha.css
Labels: help wanted

#53 Correção de estilização
  src/components/Postagem/Postagem.css
  src/pages/PerfilUsuario/PerfilUsuario.jsx
Labels: help wanted

#54 correcaoFotoPost
  src/components/Postagem/Postagem.css
  src/components/Postagem/Postagem.jsx
Labels: help wanted

#55 Correção da página de empréstimos
  src/pages/Emprestimos/Emprestimos.jsx
Labels: documentation, enhancement

#56 listagem blog
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/firebase/blog.js
  src/pages/BlogLista/BlogLista.jsx
Labels: documentation, enhancement

#58 fix rotas
  src/App.jsx
Labels: enhancement

#57 subindo as 3 tasks
  src/App.jsx
  src/assets/images/apple.png
  src/assets/images/facebook.png
  src/assets/images/gpay.png
  src/assets/images/instagram.jpg
  src/assets/images/linkedin.png
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/firebase/auth.js
  src/pages/Cadastro/Cadastro.jsx
  src/pages/EmailVerification/EmailVerification.jsx
  src/pages/NotFound/NotFound.css
  src/pages/NotFound/NotFound.jsx
Labels: documentation, enhancement

#59 Correcao footer
  src/components/Footer/Footer.css
  src/components/Footer/Footer.jsx
  src/index.css
Labels: documentation, enhancement

#60 fix btn
  src/pages/NotFound/NotFound.css
  src/pages/NotFound/NotFound.jsx
Labels: enhancement

#61 correção da tela + footer
  src/components/Footer/Footer.css
  src/pages/AdicionarEmprestimo/AdicionarEmprestimo.css
  src/pages/AdicionarEmprestimo/AdicionarEmprestimo.jsx
  src/pages/BemVindo/BemVindo.css
  src/pages/BemVindo/BemVindo.jsx
  src/pages/BlogLista/BlogLista.jsx
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Chat/Chat.css
  src/pages/Chat/Chat.jsx
  src/pages/EditarEmprestimo/EditarEmprestimo.css
  src/pages/EditarEmprestimo/EditarEmprestimo.jsx
  src/pages/Emprestimos/Emprestimos.css
  src/pages/Emprestimos/Emprestimos.jsx
  src/pages/Home/Home.jsx
  src/pages/Login/Login.jsx
  src/pages/PerfilUsuario/PerfilUsuario.css
  src/pages/RecuperacaoSenha/RecuperacaoSenha.jsx
Labels: help wanted

#62 correcao-botoes-paginação
  src/components/Footer/Footer.css
  src/pages/Cadastro/Cadastro.css
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Chat/Chat.css
  src/pages/EditarEmprestimo/EditarEmprestimo.css
Labels: help wanted

#64 fix footer
  src/components/Footer/Footer.jsx
Labels: bug
