Repository devruso/bibliotech, pull requests merged in 2023-03, with the labels that each got.

#15 exclusão livro.jsx
  src/pages/Livros/livro.jsx
Labels: duplicate

#18 Task#7 tema escuro
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/contexts/ThemeContext.js
  src/pages/AdicionarEmprestimo/AdicionarEmprestimo.jsx
  src/pages/AdicionarLivro/AdicionarLivro.jsx
  src/pages/EditarEmprestimo/EditarEmprestimo.jsx
  src/pages/EditarLivro/EditarLivro.jsx
  src/pages/Emprestimos/Emprestimos.jsx
  src/pages/Livros/Livros.jsx
Labels: enhancement

#20 autenticação com o facebook
  src/assets/icons/facebook.png
  src/firebase/auth.js
  src/pages/Cadastro/Cadastro.jsx
  src/pages/Login/Login.jsx
Labels: documentation, enhancement

#22 Área do perfil do usuário - erro ao trocar o email
  src/App.jsx
  src/components/Menu/Menu.jsx
  src/firebase/user.js
  src/pages/PerfilUsuario/PerfilUsuario.css
  src/pages/PerfilUsuario/PerfilUsuario.jsx
Labels: bug, documentation, enhancement
